version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: c2_db
    restart: unless-stopped
    environment:
      
      POSTGRES_USER: c2user
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: c2server
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes: 
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-backend
    restart: unless-stopped
    depends_on: 
      - db
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: c2user
      DB_PASSWORD: mysecretpassword
      DB_NAME: c2server
      GIN_MODE: debug
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ./binaries:/app/binaries:ro  # read-only for security

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes: # Define the named volume
  pgdata:
